/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Go to home network setup": {                    "en": "Go to home network setup",                        "de": "Gehen Sie zum Heimnetzwerk-Setup",                "ru": "Перейти к настройке домашней сети",               "pt": "Ir para a configuração da rede doméstica",        "nl": "Ga naar de installatie van het thuisnetwerk",     "fr": "Aller à la configuration du réseau domestique",   "it": "Vai alla configurazione della rete domestica",    "es": "Ir a la configuración de la red doméstica",       "pl": "Przejdź do konfiguracji sieci domowej"},
    "Go to remote device/Renderer and enter the Pre-Shared Key \"0000\" (or whatever you want your PSK Key to be)": {"en": "Go to remote device/Renderer and enter the Pre-Shared Key \"0000\" (or whatever you want your PSK Key to be)", "de": "Gehen Sie zu Remote-Gerät / Renderer und geben Sie den Pre-Shared Schlüssel \"0000\" ein (oder was auch immer Sie als PSK-Schlüssel verwenden möchten).", "ru": "Перейдите к удаленному устройству / средству визуализации и введите предварительный общий ключ «0000» (или любой другой ключ PSK)", "pt": "Ir para dispositivo / renderizador remoto e digite a chave pré-compartilhada \"0000\" (ou qualquer que seja sua chave PSK)", "nl": "Ga naar remote device / renderer en voer de pre-shared key \"0000\" in (of wat je PSK Key ook mag zijn)", "fr": "Allez au périphérique / moteur de rendu distant et entrez la clé pré-partagée \"0000\" (ou quelle que soit votre clé PSK)", "it": "Vai al dispositivo / renderer remoto e inserisci la chiave pre-condivisa \"0000\" (o qualunque sia la tua chiave PSK)", "es": "Vaya al dispositivo / renderizador remoto e ingrese la clave precompartida \"0000\" (o cualquiera que sea su clave PSK)", "pl": "Przejdź do zdalnego urządzenia / renderera i wprowadź klucz wstępny \"0000\" (lub jakikolwiek jest twój klucz PSK)"},
    "IP": {                                          "en": "IP",                                              "de": "IP",                                              "ru": "IP",                                              "pt": "IP",                                              "nl": "IP",                                              "fr": "IP",                                              "it": "IP",                                              "es": "IP",                                              "pl": "IP"},
    "IP Control - Authentication - Normal and Pre-Shared Key": {"en": "IP Control -> Authentication -> Normal and Pre-Shared Key", "de": "IP-Steuerung -> Authentifizierung -> Normal und Pre-Shared Schlüssel", "ru": "Управление IP -> Аутентификация -> Нормальный и Общий ключ", "pt": "Controle de IP -> Autenticação -> Chave Normal e Pré-Compartilhada", "nl": "IP-controle -> Authenticatie -> Normale en vooraf gedeelde sleutel", "fr": "Contrôle IP -> Authentification -> Clé normale et pré-partagée", "it": "Controllo IP -> Autenticazione -> Chiave normale e pre-condivisa", "es": "Control de IP -> Autenticación -> Clave normal y precompartida", "pl": "Kontrola IP -> Uwierzytelnianie -> Klucz normalny i wstępny"},
    "On the TV, go to Settings - Network - Home network setup": {"en": "On the TV, go to Settings -> Network -> Home network setup", "de": "Auf dem Fernsehgerät, gehen Sie zu Einstellungen -> Netzwerk -> Heimnetzwerk-Setup", "ru": "На телевизоре зайдите в Настройки -> Сеть -> Настройка домашней сети", "pt": "Na TV, vá para Configurações -> Rede -> Configuração da rede doméstica", "nl": "Ga op de tv naar Instellingen -> Netwerk -> Thuisnetwerk instellen", "fr": "Sur le téléviseur, sélectionnez Paramètres -> Réseau -> Configuration du réseau domestique.", "it": "Sul televisore, vai su Impostazioni -> Rete -> Impostazione rete domestica", "es": "En el televisor, vaya a Configuración -> Red -> Configuración de red doméstica", "pl": "W telewizorze przejdź do Ustawienia -> Sieć -> Konfiguracja sieci domowej"},
    "PSK Key": {                                     "en": "PSK Key",                                         "de": "PSK Schlüssel",                                   "ru": "PSK Key",                                         "pt": "Chave PSK",                                       "nl": "PSK-sleutel",                                     "fr": "Clé PSK",                                         "it": "Chiave PSK",                                      "es": "Clave psk",                                       "pl": "Klucz PSK"},
    "Set Simple IP Control on": {                    "en": "Set Simple IP Control on",                        "de": "Schalten Sie Simple IP Control ein",              "ru": "Установить простое управление IP на",             "pt": "Definir controle IP simples em",                  "nl": "Stel Simple IP Control in",                       "fr": "Activer le contrôle IP simple",                   "it": "Attiva Simple IP Control",                        "es": "Establecer el control de IP simple en",           "pl": "Włącz włączoną prostą kontrolę IP"},
    "Set remote device/Renderer on": {               "en": "Set remote device/Renderer on",                   "de": "Remote-Gerät / Renderer einschalten",             "ru": "Установить удаленное устройство / рендерер на",   "pt": "Definir dispositivo / renderizador remoto",       "nl": "Stel apparaat op afstand / renderer in",          "fr": "Définir le périphérique distant / le rendu sur",  "it": "Imposta il dispositivo / renderer remoto",        "es": "Poner el dispositivo / renderizador remoto en",   "pl": "Ustaw zdalne urządzenie / renderer na"},
    "TV Setup": {                                    "en": "TV Setup",                                        "de": "TV-Setup",                                        "ru": "Настройка телевизора",                            "pt": "Configuração de TV",                              "nl": "TV-instellingen",                                 "fr": "Configuration TV",                                "it": "Impostazione TV",                                 "es": "Configuración de TV",                             "pl": "Konfiguracja telewizora"},
    "Turn your TV on": {                             "en": "Turn your TV on",                                 "de": "Schalten Sie Ihren Fernseher ein",                "ru": "Включи телевизор",                                "pt": "Ligue sua TV",                                    "nl": "Schakel uw tv in",                                "fr": "Allumez votre téléviseur",                        "it": "Accendi la TV",                                   "es": "Enciende tu TV",                                  "pl": "Włącz telewizor"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.", "ru": "При сохранении адаптер перезапускается с новым конфигом немедленно.", "pt": "Em salvar adaptador reinicia com nova configuração imediatamente.", "nl": "On save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config.", "fr": "Lors de la sauvegarde, l’adaptateur redémarre immédiatement avec la nouvelle configuration.", "it": "On save adapter si riavvia immediatamente con la nuova configurazione.", "es": "En guardar adaptador se reinicia con nueva configuración de inmediato.", "pl": "Po zapisaniu adapter natychmiast uruchamia się z nową konfiguracją."},
};